
TARGET=libpng.a

all: $(TARGET)
STUBSRC = libpng.S
OBJS = \
	libpng_0000.o \
	libpng_0001.o \
	libpng_0002.o \
	libpng_0003.o \
	libpng_0004.o \
	libpng_0005.o \
	libpng_0006.o \
	libpng_0007.o \
	libpng_0008.o \
	libpng_0009.o \
	libpng_0010.o \
	libpng_0011.o \
	libpng_0012.o \
	libpng_0013.o \
	libpng_0014.o \
	libpng_0015.o \
	libpng_0016.o \
	libpng_0017.o \
	libpng_0018.o \
	libpng_0019.o \
	libpng_0020.o \
	libpng_0021.o \
	libpng_0022.o \
	libpng_0023.o \
	libpng_0024.o \
	libpng_0025.o \
	libpng_0026.o \
	libpng_0027.o \
	libpng_0028.o \
	libpng_0029.o \
	libpng_0030.o \
	libpng_0031.o \
	libpng_0032.o \
	libpng_0033.o \
	libpng_0034.o \
	libpng_0035.o \
	libpng_0036.o \
	libpng_0037.o \
	libpng_0038.o \
	libpng_0039.o \
	libpng_0040.o \
	libpng_0041.o \
	libpng_0042.o \
	libpng_0043.o \
	libpng_0044.o \
	libpng_0045.o \
	libpng_0046.o \
	libpng_0047.o \
	libpng_0048.o \
	libpng_0049.o \
	libpng_0050.o \
	libpng_0051.o \
	libpng_0052.o \
	libpng_0053.o \
	libpng_0054.o \
	libpng_0055.o \
	libpng_0056.o \
	libpng_0057.o \
	libpng_0058.o \
	libpng_0059.o \
	libpng_0060.o \
	libpng_0061.o \
	libpng_0062.o \
	libpng_0063.o \
	libpng_0064.o \
	libpng_0065.o \
	libpng_0066.o \
	libpng_0067.o \
	libpng_0068.o \
	libpng_0069.o \
	libpng_0070.o \
	libpng_0071.o \
	libpng_0072.o \
	libpng_0073.o \
	libpng_0074.o \
	libpng_0075.o \
	libpng_0076.o \
	libpng_0077.o \
	libpng_0078.o \
	libpng_0079.o \
	libpng_0080.o \

PSPSDK=$(shell psp-config --pspsdk-path)

CC=psp-gcc
INCDIR = 
CFLAGS = -std=c99 -Os -G0 -Wall -fno-builtin-printf -I$(PSPSDK)/include
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)
LDFLAGS=-nodefaultlibs

LIBDIR =

include $(ARKROOT)/common/make/global.mak
include $(ARKROOT)/common/make/beauty_stub.mak
