#ifndef _ADVANCED_H
#define _ADVANCED_H


#include "vsh.h"


enum {
	SUBMENU_USB_DEVICE,
	SUBMENU_USB_READONLY,
	SUBMENU_UMD_MODE,
	SUBMENU_UMD_VIDEO,
	SUBMENU_FG_COLORS,
	SUBMENU_BG_COLORS,
	SUBMENU_FONT,
	SUBMENU_CONVERT_BATTERY,
	SUBMENU_SWAP_XO_BUTTONS,
	SUBMENU_REGION_MODE,
	SUBMENU_UMD_REGION_MODE,
	SUBMENU_IMPORT_CLASSIC_PLUGINS,
	SUBMENU_ACTIVATE_FLASH_WMA,
	SUBMENU_DELETE_HIBERNATION,
	SUBMENU_RANDOM_GAME,
	SUBMENU_GO_BACK,
	SUBMENU_MAX
};


int submenu_draw(void);
int submenu_setup(void);
int submenu_ctrl(u32 button_on);
void subbutton_func(vsh_Menu *vsh);


#endif