TARGET          = test
OBJS            = main2.o

ARKROOT ?= $(CURDIR)/../../../


INCDIR = $(ARKROOT)/common/include
CFLAGS = -std=c99 -Os -G0 -Wall
#CFLAGS          = -Os -G0 -Wall -fshort-wchar
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS         = $(CFLAGS)
ifdef DEBUG
CFLAGS += -DDEBUG=$(DEBUG)
endif

PRX_EXPORTS		= exports.exp

PSP_FW_VERSION = 500

BUILD_PRX       = 1

#USE_KERNEL_LIBC = 1
#USE_KERNEL_LIBS = 1

LIBDIR = . $(ARKROOT)/libs ../../xmbctrl/lib
LIBS            = -lpspsystemctrl_kernel -lpspvshctrl -lpspdebug #-lpspvshctrl


PSPSDK          = $(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build_prx.mak
